version: '3.8'

services:
  loginapp:
    build:
      context: .
      dockerfile: ./loginapi.Dockerfile
    container_name: loginapi
    restart: unless-stopped
    ports:
      - 443:443  # HTTPS
    networks:
      - internal
  smtp:
    #image: namshi/smtp
    build:
      context: .
      dockerfile: ./smtp.Dockerfile
    container_name: smtp
    restart: unless-stopped
    ports:
      - 8025:8025  # SMTP
    networks:
      - internal
networks:
  internal:
    name: internal
    external: true